### ISSUE TITLE
Questions on Frontend Test - Yi Zu

### ISSUE THREAD

**Issue by yizucodes** [satispay/frontend-assignment#7]
Hi @bwlt,

Hope all is well! My name is Yi and I am a candidate for the [frontend developer position](https://satispay.breezy.hr/p/c30bfc5a749101-front-end-developer) at Satispay. I had a few questions on the test:

What do you mean by **"Do you master your working environment?"** as one of your evaluation criteria?
May I use **create-react-app** to setup the web application?

Thank you for your time.

Best,
Yi

**Comment by bwlt** [comment]
Hi @yizucodes

> What do you mean by "Do you master your working environment?" as one of your evaluation criteria?

We mean that we expect from the candidate to master and be confident with the technology / tooling, using modern and smart solutions to reach the goal.

>  May I use create-react-app to setup the web application?

Yes, of course :)
